# Generated by Django 4.1.3 on 2023-01-28 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='title',
            new_name='login',
        ),
        migrations.AddField(
            model_name='chat',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='Пароль'),
            preserve_default=False,
        ),
    ]
