# Generated by Django 4.1.3 on 2023-02-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_chat_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.CharField(default='default', max_length=1000, verbose_name='Автор'),
        ),
    ]
